### ISSUE TITLE
redirect users to intended page (dynamically)

### ISSUE THREAD

**Issue by bchr02** [Azure-Samples/microsoft-identity-express#39]
# Issue
## This issue is for a
```console
    - [x] question
```
When calling the /signin route with parameters (e.g. ```/signin?callingURL=https%3A%2F%2Fgoogle.com```) the parameters are not passed to postLogoutRedirect. Is there any way to preserve req.qurey? I am trying to redirect the user back to the intended page (in a dynamic way) following a signin. In other words I don't want the postLogoutRedirect to be static. Thanks.

**Comment by derisen** [comment]
Hi @bchr02 -could you explain your scenario a bit more? Why won't the `postLoginRedirect` suffice here? Currently the query strings are ignored but we could certainly look into supporting it.

**Comment by bchr02** [comment]
Hi @derisen Never mind. I figured it out. Thank you.

instead of this:
```javascript
router.get('/signin', msid.signIn({
    postLoginRedirect: '/where_do_i_go'
}));
```
I did this:
```javascript
router.get('/signin', function (req, res, next) {
        msid.signIn({
            postLoginRedirect: req.get("Referrer")
        })(req, res, next);
    }
);
```
