### ISSUE TITLE
isAuthenticated() not redirecting users to sign in

### ISSUE THREAD

**Issue by joraff** [Azure-Samples/microsoft-identity-express#41]
Hi,

According to the [documentation](https://github.com/Azure-Samples/microsoft-identity-express/blob/c00ce7b8cd3afcbe42a516f53de1e31f2711945c/README.md?plain=1#L189) I should be able to add `isAuthenticated()` into the middleware chain to protect routes, with an optional route to redirect to (such as to send them to sign-in).

https://github.com/Azure-Samples/microsoft-identity-express/blob/c00ce7b8cd3afcbe42a516f53de1e31f2711945c/README.md?plain=1#L194-L196

However, I'm not seeing where that unauthorized route is ever used:

https://github.com/Azure-Samples/microsoft-identity-express/blob/c00ce7b8cd3afcbe42a516f53de1e31f2711945c/src/client/webapp/MsalWebAppAuthClient.ts#L318-L332

Ideally, I'd like the user to be redirected to MSAAD for sign-in if `req.session.isAuthenticated` is false, and I did this in my own middleware. But am I missing something that's included in this project?

Thank you!

**Comment by derisen** [comment]
@joraff apologies for misleading documentation, this hasn't been implemented yet (there's currently a PR that will handle this case better, but you are also welcome to suggest one)

For the moment, you could handle this in your router like:

```JavaScript
const express = require('express');
const mainController = require('../controllers/mainController');

module.exports = (msid) => {
    
    // initialize router
    const router = express.Router();
     
    router.get('/signin',
      msid.signIn({
          postLoginRedirect: "/",
          failureRedirect: "/signin"
      }));
        
    // ...
  
    // unauthorized
    router.get('/unauthorized', (req, res, next) => {
         res.redirect('/signin')
    });

    return router;
}
```

Would that help?
