### ISSUE TITLE
Handling separate sign in and sign up B2C user flows

### ISSUE THREAD

**Issue by karmus89** [Azure-Samples/microsoft-identity-express#46]
I'm trying to create a B2C authentication solution with separate user flows for singing in and signing up for more granular control. Is it possible to utilize this library to create a separate .../sing-up handle? If so, what steps should I look to take?

**Comment by derisen** [comment]
Hi @karmus89 , apologies for the late response. This is currently not supported by the package but it is in our backlog. You are also more than welcome to open a PR to introduce this feature. I'll keep this open until a solution is available.
